"""empty message

Revision ID: 6e291ab98846
Revises: 7df0d9550c64
Create Date: 2019-01-19 10:07:19.641315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e291ab98846'
down_revision = '7df0d9550c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('post', sa.Column('pubdate', sa.String(length=10), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(length=64), nullable=True))
    op.add_column('post', sa.Column('uniqueid', sa.String(length=8), nullable=False))
    op.add_column('post', sa.Column('videourl', sa.String(length=256), nullable=True))
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_column('post', 'id')
    op.drop_column('post', 'timestamp')
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.add_column('post', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('post', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_column('post', 'videourl')
    op.drop_column('post', 'uniqueid')
    op.drop_column('post', 'title')
    op.drop_column('post', 'pubdate')
    op.drop_column('post', 'description')
    # ### end Alembic commands ###
